<Project Sdk="Microsoft.NET.Sdk">

  <!-- Estas propiedades se definen en el archivo global Directory.Build.props -->
  <!-- <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup> -->

</Project>